In [ ]:
import numpy as np 
import math

# Cau 1
A = np.array([2,-1,3,0])
B = np.array([1,4,-2,5])
C = np.array([[1,2,-1],[0,3,4],[2,-1,0]])

#a
tong = A + B
tich = 3*A - 2*B

#b tich vo huong
np_dot = np.dot(A,B)
# Goc giua 2 vecto
magnitude_A = np.linalg.norm(A)
magnitude_B = np.linalg.norm(B)
cos_angle = np_dot / (magnitude_A * magnitude_B)
angle_rad = np.arccos(cos_angle)
angle_deg = np.degrees(angle_rad)


#c 
C_trans = C.T
nghich_dao_C = np.dot(C_trans,C)
print("C_trans = ", C_trans)
print("C.T = ", nghich_dao_C)

print("A = ", A)
print("B = ", B)
print("C = ", C)
print("Tong = ", tong)
print("Tich = ", tich)
print("Tich vo huong = ", np_dot)
print("Goc A = ", magnitude_A)
print("Goc B = ", magnitude_B)
print(cos_angle)
print(angle_deg)
print(angle_rad)


C_trans =  [[ 1  0  2]
 [ 2  3 -1]
 [-1  4  0]]
C.T =  [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]
A =  [ 2 -1  3  0]
B =  [ 1  4 -2  5]
C =  [[ 1  2 -1]
 [ 0  3  4]
 [ 2 -1  0]]
Tong =  [3 3 1 5]
Tich =  [  4 -11  13 -10]
Tich vo huong =  -8
Goc A =  3.7416573867739413
Goc B =  6.782329983125268
-0.31524416249564025
108.3755542856849
1.891510250959053


In [17]:
#Cau 2

from sympy import det


M = np.array([[1,2,3,0],
              [4,5,6,1],
              [7,8,9,2],
              [0,1,1,0]])
N = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11],
              [12,13,14,15]])
print("M = ",M)
print("N = ",N)

#a Tich ma tran M*N
tich = np.dot(M,N)
print("Tich = ",tich)

#b Tinh dinh thuc mt M
det_M = np.linalg.det(M)
print("det_M = ",det_M)

if abs(det_M) > 0.0001:
    print("M kha nghich")
else:
    print("M ko kha nghich")

#C Hang cua N
N_np = np.array(N)
rank_N = np.linalg.matrix_rank(N_np)
print("Rank(N) = ",rank_N)

M =  [[1 2 3 0]
 [4 5 6 1]
 [7 8 9 2]
 [0 1 1 0]]
N =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Tich =  [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]
det_M =  6.66133814775094e-16
M ko kha nghich
Rank(N) =  2


In [21]:
# Cau 3
P = np.array([[2,1,0,1],
      [0,3,1,-1],
      [1,0,4,2],
      [0,1,0,3]])
PTTT = ([4,7,9,5])

#a Ma tran nghich dao P
det_P = np.linalg.det(P)
print("det_P = ",det_P)

if abs(det_P) > 0.0001:
    P_inv = np.linalg.inv(P)
    print(f"P kha nghich")
    print(f"P^(-1) = ")
    
    for i in range(len(P_inv)):
        row = []
        for j in range(len(P_inv)):
            row.append(round(P_inv[i][j], 4))
        print(" ",row)
else:
    print(f"P khong kha nghich")

#b Giai he phuong trinh
if abs(det_P) > 0.0001:
    giai_phap = np.dot(P_inv,PTTT)
    print(f"Nghiem: ")
    print(f"x = ",round(giai_phap[0], 4))
    print(f"y = ",round(giai_phap[1], 4))
    print(f"z = ",round(giai_phap[2], 4))
    print(f"w = ",round(giai_phap[3], 4))
#c Kiem tra
    kt = np.dot(P, giai_phap)
    print("   2x + y + w =", round(kt[0], 4), "(phải = 4)")
    print("   3y + z - w =", round(kt[1], 4), "(phải = 7)")
    print("   x + 4z + 2w =", round(kt[2], 4), "(phải = 9)")
    print("   y + 3w =", round(kt[3], 4), "(phải = 5)")
else:
    print("b) Không thể giải vì P không khả nghịch")

det_P =  86.00000000000004
P kha nghich
P^(-1) = 
  [0.4884, -0.093, 0.0233, -0.2093]
  [0.0349, 0.2791, -0.0698, 0.1279]
  [-0.1163, 0.0698, 0.2326, -0.093]
  [-0.0116, -0.093, 0.0233, 0.2907]
Nghiem: 
x =  0.4651
y =  2.1047
z =  1.6512
w =  0.9651
   2x + y + w = 4.0 (phải = 4)
   3y + z - w = 7.0 (phải = 7)
   x + 4z + 2w = 9.0 (phải = 9)
   y + 3w = 5.0 (phải = 5)


In [25]:
import math
Q = np.array([[4,-1,0],
              [1,3,-2],
              [0,1,2]])
print("Q = ",Q)
for row in Q:
    print(row)
Q_np = np.array(Q)
values,vectors = np.linalg.eig(Q_np)

#a
for i in range(3):
    print(f"lambda{i+1} = {values[i]}:.4f")
#b
for i in range(3):
    v = vectors[:,i]
    print(f"v{i+1} = [{v[0]:.4f},{v[1]:.4f},{v[2]:.4f}]")

Q =  [[ 4 -1  0]
 [ 1  3 -2]
 [ 0  1  2]]
[ 4 -1  0]
[ 1  3 -2]
[0 1 2]
lambda1 = (3.4533976515164015+0j):.4f
lambda2 = (2.773301174241798+1.4677115087102246j):.4f
lambda3 = (2.773301174241798-1.4677115087102246j):.4f
v1 = [0.8333+0.0000j,0.4555+0.0000j,0.3134+0.0000j]
v2 = [-0.2621-0.3135j,-0.7817+0.0000j,-0.2196+0.4169j]
v3 = [-0.2621+0.3135j,-0.7817-0.0000j,-0.2196-0.4169j]
