LAB 6

1.2. Tích vô hướng

In [5]:
import numpy as np 
import math

a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b)
print(tich)

32


In [2]:
print(np.dot(a,b))

32


In [3]:
a = np.array([1,2,-3])
print(np.linalg.norm(a))

3.7416573867739413


In [6]:
def chuan(v,k):
    tong = 0
    for i in range(len(v)):
        tong = tong + abs(v[i]**k)
    ketqua = math.pow(tong, 1.0/k)
    return ketqua

a = np.array([1,2,-3])
print(chuan(a,1))

6.0


In [7]:
print(np.linalg.norm(a,1))

6.0


In [8]:
print(chuan(a,2))

3.7416573867739413


In [9]:
print(np.linalg.norm(a,2))


3.7416573867739413


2. 

In [13]:
import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])
M = np.array([v1,v2,v3,v4])
MT = M.transpose()
print("MT = ",MT)

v = (1.0/m)*MT.dot(mi)
print("v = ",v)

MT =  [[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]
v =  [1.3 0.9 0. ]


3. 

In [14]:
import numpy as np

# Khai báo ma trận chuyển trạng thái A
A = np.array([[0.998, 0.136],
              [0.002, 0.864]])

# Khai báo vector trạng thái ban đầu v0
v0 = np.array([[0.95],
               [0.05]])

# Tính A^100 sử dụng matrix_power
A_100 = np.linalg.matrix_power(A, 100)

# Tính trạng thái sau 100 tuần: v_100 = A^100 * v0
v_100 = np.dot(A_100, v0)

# In kết quả
print("Tỷ lệ có việc làm sau 100 tuần:", v_100[0, 0])
print("Tỷ lệ thất nghiệp sau 100 tuần:", v_100[1, 0])


Tỷ lệ có việc làm sau 100 tuần: 0.9855072337572737
Tỷ lệ thất nghiệp sau 100 tuần: 0.01449276624272995


In [15]:
import sympy as sym

x, y = sym.symbols('x y')
xy = sym.Matrix([x,y]) # khai báo vector: (x, y)T
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v]) # phương trình được chuyển về 1 phía
print(sym.pretty(nghiem)) 

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


3.2.

In [16]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])

print (sympy.pretty(nghiem))

[-7.000, 3.000]
[-7, 3]


3.3.

In [19]:
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P) # tính giá trị nghịch đảo của P
print ("P1 = ",P1)

print("A.dot = ",A.dot(P))
print("P.dot = ",P.dot(D))

print(P @ (D ** 1000) @ P1)

print("D^2 = ", D**2)

P1 =  [[-0.3  0.9]
 [ 0.3  0.1]]
A.dot =  [[ 2.33333333  9.        ]
 [-7.          3.        ]]
P.dot =  [[ 2.33333333  9.        ]
 [-7.          3.        ]]
[[-6.25396533e+08 -3.52488701e+08]
 [-3.52488701e+08  3.14573335e+08]]
D^2 =  [[49  0]
 [ 0  9]]


BÀI TẬP CHƯƠNG

BÀI 2 

In [ ]:
# a

import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

distance = np.linalg.norm(u - v)
print("Khoảng cách giữa u và v:", distance)


In [20]:
# b
import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

cos_theta = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))
theta_rad = np.arccos(cos_theta)

print("Góc θ (radian):", theta_rad)
print("Góc θ (độ):", np.degrees(theta_rad))


Góc θ (radian): 0.2257261285527342
Góc θ (độ): 12.933154491899135


In [21]:
# c
import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

projection_scalar = np.dot(u, v) / np.dot(v, v)
p = projection_scalar * v

print("Phép chiếu của u lên v là vector:", p)


Phép chiếu của u lên v là vector: [1.66233766 2.07792208 2.49350649]
