Cau 1

In [ ]:
import numpy as np 
from numpy.linalg import eig,norm
import sympy as sp 

A = np.array([3,-2,1,4])
B = np.array([-1,5,0,2])
C = np.array([[2,-1,3],
            [1,4,-2],
            [0,2,5]])

print(f"Cau a")
tong = A + B
tich = 2*A +3*B
print("Tong = ",tong)
print("Tich = ",tich)

print(f"Cau b")
np_dot = np.dot(A,B)
print("Tich vo huong = ",np_dot)

magnitude_A = np.linalg.norm(A)
magnitude_B = np.linalg.norm(B)
cos_angle = np_dot / (magnitude_A * magnitude_B)
angle_rad = np.arccos(cos_angle)
angle_deg = np.degrees(angle_rad)
print("Goc A = ", magnitude_A)
print("Goc B = ", magnitude_B)
print(round(cos_angle,3))
print(round(angle_deg,3))
print(round(angle_rad,3))

print(f"Cau c")
C_transpose = C.T
print("CC^T = ",C_transpose)
tinh_tich_CC_T = np.dot(C,C_transpose)
print("Tich CC^T = ",tinh_tich_CC_T)



Cau a
Tong =  [2 3 1 6]
Tich =  [ 3 11  2 14]
Cau b
Tich vo huong =  -5
Goc A =  5.477225575051661
Goc B =  5.477225575051661
-0.167
99.594
1.738
Cau c
CC^T =  [[ 2  1  0]
 [-1  4  2]
 [ 3 -2  5]]
Tich CC^T =  [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


Cau 2

In [21]:
M = np.array([[2,-1,3,0],
                [1,4,-2,5],
                [0,2,6,-3],
                [-1,0,1,4]])
N = np.array([[1,3,-2,0],
                [4,-1,5,2],
                [0,2,3,-1],
                [-3,1,0,4]])

print(f'Cau a')
tich_M_N = np.dot(M,N)
print("Tich ma tran M_N = ",tich_M_N)

print(f'Cau b')
det_M = np.linalg.det(M)
print("det_M = ",round(det_M,1))
if abs(det_M) > 0.0001:
    print("M kha nghich")
else:
    print("M ko kha nghich")
print(f"Cau c")
rank_N = np.linalg.matrix_rank(N)
print("rank_N = ",rank_N)

Cau a
Tich ma tran M_N =  [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
Cau b
det_M =  409.0
M kha nghich
Cau c
rank_N =  4


Cau 3

In [27]:
P = np.array([[3,-1,0,2],
                [1,4,-2,0],
                [0,1,5,-1],
                [2,0,1,3]])
pt = ([6,8,3,7])

print(f'Cau a')
mtnd_P = np.linalg.det(P)
if abs(mtnd_P) > 0.0001:
    P_inv = np.linalg.inv(P)
    print(f"P kha nghich")
    print(f"P^(-1) = ")
    
    for i in range(len(P_inv)):
        row = []
        for j in range(len(P_inv)):
            row.append(round(P_inv[i][j], 4))
        print(" ",row)
else:
    print(f"P khong kha nghich")

print(f'Cau b')
if abs(mtnd_P) > 0.0001:
    giai_phap = np.dot(P_inv,pt)
    print(f"Nghiem: ")
    print(f"x = ",round(giai_phap[0], 4))
    print(f"y = ",round(giai_phap[1], 4))
    print(f"z = ",round(giai_phap[2], 4))
    print(f"w = ",round(giai_phap[3], 4))
#c Kiem tra
    kt = np.dot(P, giai_phap)
    print("   2x + y + w =", round(kt[0], 4), "(phải = 6)")
    print("   3y + z - w =", round(kt[1], 4), "(phải = 8)")
    print("   x + 4z + 2w =", round(kt[2], 4), "(phải = 3)")
    print("   y + 3w =", round(kt[3], 4), "(phải = 7)")
    print(f"P khả nghịch")
else:
    print("b) Không thể giải vì P không khả nghịch")

Cau a
P kha nghich
P^(-1) = 
  [0.5, 0.1, 0.1, -0.3]
  [-0.1429, 0.2, 0.0571, 0.1143]
  [-0.0357, -0.05, 0.1643, 0.0786]
  [-0.3214, -0.05, -0.1214, 0.5071]
Cau b
Nghiem: 
x =  2.0
y =  1.7143
z =  0.4286
w =  0.8571
   2x + y + w = 6.0 (phải = 6)
   3y + z - w = 8.0 (phải = 8)
   x + 4z + 2w = 3.0 (phải = 3)
   y + 3w = 7.0 (phải = 7)
P khả nghịch


Cau 4

In [ ]:
Q = np.array([[5,-2,1],[0,3,-1],[2,0,4]])
print("Q = ",Q)

print(f'Cau a')
gtr,Vecto_rieng_Q = np.linalg.eig(Q)
print(f'Gia tri rieng')
for i, val in enumerate(gtr):
    print(f"lamda{i+1} = {val:.6f}")

print(f'Cau b')
print(f'Vecto rieng')
for i, vec in enumerate(Vecto_rieng_Q):
    print(f'v{i+1} = {vec}')

print(f'Cau c')


Q =  [[ 5 -2  1]
 [ 0  3 -1]
 [ 2  0  4]]
Cau a
Gia tri rieng
lamda1 = 6.355301+0.000000j
lamda2 = 2.822349+1.077304j
lamda3 = 2.822349-1.077304j
Cau b
Vecto rieng
v1 = [ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
v2 = [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
v3 = [0.63555359+0.j 0.63555359+0.j 0.63555359-0.j]


Cau 5

In [44]:
R = np.array([[4,-1,2],[1,3,-2],[0,2,5]])
vecto_b = [12,5,9]
print('R = ',R)
print('vecto_b =',vecto_b)

try:
    x = np.linalg.solve(R, vecto_b)
    print(f"Nghiệm: x = {x}")
    print(f"x₁ = {x[0]:.6f}")
    print(f"x₂ = {x[1]:.6f}")  
    print(f"x₃ = {x[2]:.6f}")
    print()
    
    # Kiểm tra nghiệm
    print("Kiểm tra nghiệm:")
    Rx = R @ x
    print(f"Rx = {Rx}")
    print(f"b  = {vecto_b}")
    print(f"Sai số ||Rx - b|| = {np.linalg.norm(Rx - vecto_b):.2e}")
    
    # Kiểm tra từng phương trình
    print("\nKiểm tra từng phương trình:")
    for i in range(3):
        left_side = np.dot(R[i], x)
        print(f"Phương trình {i+1}: {left_side:.6f} = {vecto_b[i]} ✓")
        
except np.linalg.LinAlgError as e:
    print(f"Lỗi: {e}")
    print("Hệ phương trình có thể không có nghiệm duy nhất")

R =  [[ 4 -1  2]
 [ 1  3 -2]
 [ 0  2  5]]
vecto_b = [12, 5, 9]
Nghiệm: x = [2.78823529 1.52941176 1.18823529]
x₁ = 2.788235
x₂ = 1.529412
x₃ = 1.188235

Kiểm tra nghiệm:
Rx = [12.  5.  9.]
b  = [12, 5, 9]
Sai số ||Rx - b|| = 0.00e+00

Kiểm tra từng phương trình:
Phương trình 1: 12.000000 = 12 ✓
Phương trình 2: 5.000000 = 5 ✓
Phương trình 3: 9.000000 = 9 ✓
