In [2]:
import numpy as np
#a
u = np.array([2,-1,5,0])
v = np.array([4,3,1,-1])
w = np.array([-6,2,0,3])
x = 2*u-(v+3*w)
print("x = ",x)

#b 
x1 = 0.5*(2*u-v-3*w)
print("x1 = ",x1)

x =  [ 18 -11   9  -8]
x1 =  [ 9.  -5.5  4.5 -4. ]


Bài toán 2

In [3]:
from numpy import linalg
A = np.matrix([[0,-1,3],[1,1,1],[4,2,2]])
B = np.array([-1,-2,-2])
X = np.linalg.solve(A,B)
print("X = ",X)

X =  [ 1. -2. -1.]


Bai toan 3

In [4]:
A1 = np.matrix([[1,0],[0,0]])
B1 = np.matrix([[0,0],[0,1]])
from numpy import linalg as LA 

print(LA.inv(A1))
print(LA.inv(B1))
print(LA.inv(A1+B1))
print(LA.det(A1))
print(LA.det(B1))
print(LA.det(A1+B1))




LinAlgError: Singular matrix

Bai toan 4

In [ ]:
import sympy as sp 
x, y = sp.symbols('x y') # khai báo 2 biến x và y
A = sp.Matrix([[x, y],[y, x]]) # lưu ý: kiểu ma trận của sympy là ‘Matrix’ (viết hoa)
x1, y1 = sp.symbols('x1 y1')
A1 = sp.Matrix([[x1, y1],[y1, x1]])
x2, y2 = sp.symbols('x2 y2')
A2 = sp.Matrix([[x2, y2],[y2, x2]])
print(A1.T)
print(A1+A2).T
print(((A1+A2).T).equals(A1+A2))
c = sp.symbols('c')
print (c*A)
print(((c*A).T).equals(c*A))

Bai toan 5

In [5]:
import numpy as np

# Các vector cơ sở
v1 = np.array([1, 2, 3])
v2 = np.array([0, 1, 2])
v3 = np.array([-1, 0, 1])

# a. Kiểm tra w = (1, 1, 1)
w1 = np.array([1, 1, 1])
A = np.column_stack((v1, v2, v3))
c, residuals, rank, s = np.linalg.lstsq(A, w1, rcond=None)
print("a. w1 là tổ hợp tuyến tính:", np.allclose(A @ c, w1))

# b. Kiểm tra w = (1, -2, 2)
w2 = np.array([1, -2, 2])
c, residuals, rank, s = np.linalg.lstsq(A, w2, rcond=None)
print("b. w2 là tổ hợp tuyến tính:", np.allclose(A @ c, w2))


a. w1 là tổ hợp tuyến tính: True
b. w2 là tổ hợp tuyến tính: False


Bai toan 6

In [6]:
import sympy as sp

# Khai báo 3 ẩn
c1, c2, c3 = sp.symbols('c1 c2 c3')

# Các vector v1 = (1,2,3), v2 = (0,1,2), v3 = (-2,0,1)
# Giải hệ: c1*v1 + c2*v2 + c3*v3 = 0
eq1 = c1 + 0*c2 + (-2)*c3
eq2 = 2*c1 + 1*c2 + 0*c3
eq3 = 3*c1 + 2*c2 + 1*c3

# Giải hệ phương trình
solution = sp.solve([eq1, eq2, eq3], (c1, c2, c3))
print("Nghiệm của hệ là:", solution)


Nghiệm của hệ là: {c1: 0, c2: 0, c3: 0}


Baitoan7

In [7]:
c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')
print(sp.solve([c1+c2-u1,c1-c2-u2]))

u1 = 0
u2 = 0
print(sp.solve([c1+c2-u1,c1-c2-u2]))

{c1: u1/2 + u2/2, c2: u1/2 - u2/2}
{c1: 0, c2: 0}


II.

In [13]:
#a 
import numpy as np

P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,2])

# Tịnh tiến điểm
P_caua = (P.T + vecdelta).T
print(P_caua)


[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]


In [12]:
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,-2])
matran_biendoi = np.array([[1.0, 0.0], [0.0, 2.0]])

P_caub = (P.T @ matran_biendoi + vecdelta).T
print(P_caub)


[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]


In [11]:
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4, 2])  # dịch (0,0) sang (4,2)
matran_doitrucy = np.array([[-1, 0], [0, 1]])

P_cauc = (P.T @ matran_doitrucy + vecdelta).T
print(P_cauc)


[[4 4 1 1 3 3 2 2 3 3]
 [2 7 7 6 6 5 5 4 4 2]]


In [10]:
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([2, -1])
matran_shear = np.array([[1, 1.5], [0, 1]])  # shearing theo trục x

P_caud = (P.T @ matran_shear + vecdelta).T
print(P_caud)


[[ 2.   2.   5.   5.   3.   3.   4.   4.   3.   3. ]
 [-1.   4.   8.5  7.5  4.5  3.5  5.   4.   2.5  0.5]]


In [9]:
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
matran_dxy0 = np.array([[-1, 0], [0, 1]])

P_dxy0 = (P.T @ matran_dxy0).T
print(P_dxy0)


[[ 0  0 -3 -3 -1 -1 -2 -2 -1 -1]
 [ 0  5  5  4  4  3  3  2  2  0]]


In [8]:
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
matran_dx_y = np.array([[0, 1], [1, 0]])

P_dyx = (P.T @ matran_dx_y).T
print(P_dyx)


[[0 5 5 4 4 3 3 2 2 0]
 [0 0 3 3 1 1 2 2 1 1]]


III.

In [ ]:
from sympy import *

x1,x2,x3 = sp.symbols('x1 x2 x3')
bieuthuc1 = x1-x2+x3
f1 = lambdify([x1,x2,x3],bieuthuc1,'numpy')
a,b,c = sp.symbols('a b c')
d,e,f = sp.symbols('d e f')
print(f1(a b c))

<function _lambdifygenerated at 0x0000021539EFF600>


In [19]:
a,b = sp.symbols('a b')
x,y = sp.symbols('x y')
print(sp.solve([a+3*b-x,2*a+5*b-y],[a,b]))

fu1 = np.array([1,1,2])
fu2 = np.array([4,2,1])
fu = a*fu1 + b*fu2
print("fu = ",fu)

fu = a.subs(a, -5*x + 3*y)*fu1 + b.subs(b, 2*x - y)*fu2
print("fu = ",fu)

{a: -5*x + 3*y, b: 2*x - y}
fu =  [a + 4*b a + 2*b 2*a + b]
fu =  [3*x - y -x + y -8*x + 5*y]


In [20]:
x1,x2,x3 = sp.symbols('x1 x2 x3')
print(sp.solve([x1+x2-x3, 2*x1+3*x2-x3, 3*x1+5*x2-x3],[x1, x2, x3]))

{x1: 2*x3, x2: -x3}


In [21]:
import math
from scipy import linalg as LA 
B = np.matrix([[1.0/math.sqrt(2),1.0/math.sqrt(2)],[-1.0/math.sqrt(2),1.0/math.sqrt(2)]])
print(LA.orth(B))

[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


Cau 1

In [22]:
from sympy import symbols, Matrix, simplify

x, y, z = symbols('x y z')
u = Matrix([x, y, z])
g = Matrix([x + y, z + 2, 0])

# Kiểm tra tuyến tính: g(a*u) == a*g(u)?
a = symbols('a')
lhs = g.subs({x: a*x, y: a*y, z: a*z})
rhs = a * g
print("g(a*u):", lhs)
print("a * g(u):", simplify(rhs))

print("Là ánh xạ tuyến tính?", simplify(lhs - rhs) == Matrix([0,0,0]))


g(a*u): Matrix([[a*x + a*y], [a*z + 2], [0]])
a * g(u): Matrix([[a*(x + y)], [a*(z + 2)], [0]])
Là ánh xạ tuyến tính? False


Cau 2

In [ ]:
import numpy as np

# Tập điểm ví dụ F gồm các điểm (x, y)
F = np.array([[1, 2, 3], [4, 5, 6]])  # 3 điểm: (1,4), (2,5), (3,6)

# Ma trận biến đổi: f(x, y) = (y, x - y)
# --> ứng với nhân bởi ma trận:
mat = np.array([[0, 1], [1, -1]])

F_transformed = mat @ F
print(F_transformed)


Cau 3

In [ ]:
from sympy import symbols, Matrix

v1, v2 = symbols('v1 v2')
v = Matrix([v1, v2])
T = Matrix([v1 - v2, v1 + 2*v2])

a = symbols('a')

# Kiểm tra T(a * v) == a * T(v)?
lhs = T.subs({v1: a*v1, v2: a*v2})
rhs = a * T

print("Là ánh xạ tuyến tính?", simplify(lhs - rhs) == Matrix([0,0]))
