In [1]:
import numpy as np
from scipy import linalg
import matplotlib.pyplot as plt

1. CÁC PHÉP XỬ LÝ MA TRẬN CƠ BẢN

In [2]:
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])  # số phức
c = np.array([[(0.5, 1.5, 10), (3, 2, 1)], [(6, 5, 4), (7, 8, 9)]])

# Các cách tạo ma trận khác nhau
A = np.matrix(np.random.random((2, 2)))
B = np.asmatrix(b)
C = np.mat(np.random.random((10, 5)))
D = np.mat([[4, 3], [2, 6]])

# Ma trận đường chéo
F_k1 = np.eye(3, k=1)   # đường chéo phía trên
F_k0 = np.eye(3, k=0)   # đường chéo chính
F_k_1 = np.eye(3, k=-1) # đường chéo phía dưới

print("Ma trận A:")
print(A)
print("\nMa trận D:")
print(D)

# Các phép xử lý cơ bản
print(f"\nHạng của ma trận C: {np.linalg.matrix_rank(C)}")
print(f"Định thức của A: {linalg.det(A)}")

# Ma trận nghịch đảo
print("\nMa trận nghịch đảo A.I:")
print(A.I)
print("\nMa trận nghịch đảo linalg.inv(A):")
print(linalg.inv(A))

# Chuyển vị
print("\nChuyển vị A.T:")
print(A.T)

# Các phép toán ma trận
print("\nCộng ma trận A + D:")
print(np.add(A, D))

print("\nNhân ma trận A @ D:")
print(A @ D)

print("\nNhân element-wise np.multiply(A, D):")
print(np.multiply(A, D))


Ma trận A:
[[0.54455556 0.38022359]
 [0.98829554 0.24972975]]

Ma trận D:
[[4 3]
 [2 6]]

Hạng của ma trận C: 5
Định thức của A: -0.2397815590657598

Ma trận nghịch đảo A.I:
[[-1.04148855  1.58570823]
 [ 4.1216495  -2.27104855]]

Ma trận nghịch đảo linalg.inv(A):
[[-1.04148855  1.58570823]
 [ 4.1216495  -2.27104855]]

Chuyển vị A.T:
[[0.54455556 0.98829554]
 [0.38022359 0.24972975]]

Cộng ma trận A + D:
[[4.54455556 3.38022359]
 [2.98829554 6.24972975]]

Nhân ma trận A @ D:
[[2.93866944 3.91500824]
 [4.45264167 4.46326511]]

Nhân element-wise np.multiply(A, D):
[[2.17822225 1.14067078]
 [1.97659109 1.49837848]]


2. BÀI TOÁN SIÊU THỊ

In [ ]:
# Ma trận nhu cầu (người x sản phẩm)
demand = np.array([
    [6, 5, 3, 1],  # Cảnh
    [3, 6, 2, 2],  # Nhật
    [3, 4, 3, 1]   # Hiếu
])

# Ma trận giá (sản phẩm x siêu thị)
prices = np.array([
    [1.50, 1.00],  # Cồn
    [2.00, 2.50],  # Nước rửa tay
    [5.00, 4.50],  # Khẩu trang
    [16.00, 17.00] # Bánh mì
])

# Tính tổng chi phí
total_cost = demand @ prices
print("Tổng chi phí mỗi người tại mỗi siêu thị:")
print("        S1      S2")
for i, name in enumerate(['Cảnh', 'Nhật', 'Hiếu']):
    print(f"{name:5}: {total_cost[i,0]:6.2f}  {total_cost[i,1]:6.2f}")
    cheaper = "S1" if total_cost[i,0] < total_cost[i,1] else "S2" if total_cost[i,0] > total_cost[i,1] else "Cả hai"
    print(f"      -> Nên mua tại: {cheaper}")

3. MA TRẬN HỘI TỤ VÀ PHÂN KỲ

In [3]:
def test_matrix_convergence(matrix, name, max_iterations=10):
    print(f"\nKiểm tra ma trận {name}:")
    print(f"Ma trận gốc:\n{matrix}")
    
    temp = matrix.copy()
    for i in range(max_iterations):
        temp = temp @ matrix
        print(f"Lũy thừa {i+2}:\n{temp}")
        if i >= 2:  # Chỉ in 3 lần đầu để tiết kiệm không gian
            break
    
    # Kiểm tra hội tụ với nhiều lần lặp
    temp = matrix.copy()
    for i in range(1000):
        temp = temp @ matrix
    print(f"Sau 1000 lần lặp:\n{temp}")

# Ma trận phân kỳ
A_divergent = np.array([[0, 1], [1, 0]])
B_divergent = np.array([[0, -1], [-1, 0]])

# Ma trận hội tụ
C_convergent = np.array([[1, 0, 0], [0, 0.5, 1], [0, 0, 0.5]])

test_matrix_convergence(A_divergent, "A (phân kỳ)", 5)
test_matrix_convergence(C_convergent, "C (hội tụ)", 5)


Kiểm tra ma trận A (phân kỳ):
Ma trận gốc:
[[0 1]
 [1 0]]
Lũy thừa 2:
[[1 0]
 [0 1]]
Lũy thừa 3:
[[0 1]
 [1 0]]
Lũy thừa 4:
[[1 0]
 [0 1]]
Sau 1000 lần lặp:
[[0 1]
 [1 0]]

Kiểm tra ma trận C (hội tụ):
Ma trận gốc:
[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
Lũy thừa 2:
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
Lũy thừa 3:
[[1.    0.    0.   ]
 [0.    0.125 0.75 ]
 [0.    0.    0.125]]
Lũy thừa 4:
[[1.     0.     0.    ]
 [0.     0.0625 0.5   ]
 [0.     0.     0.0625]]
Sau 1000 lần lặp:
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]


4. MA TRẬN MARKOV

In [ ]:
def analyze_markov_matrix(M, name, iterations=100):
    print(f"\nPhân tích ma trận Markov {name}:")
    print(f"Ma trận ban đầu:\n{M}")
    
    # Tính các lũy thừa đầu tiên
    M2 = M @ M
    M3 = M2 @ M
    print(f"M^2:\n{M2}")
    print(f"M^3:\n{M3}")
    
    # Tính trạng thái ổn định
    temp = M.copy()
    for i in range(iterations):
        temp = temp @ M
    
    print(f"Trạng thái ổn định (sau {iterations} lần):\n{temp}")
    return temp

# Ma trận Markov cho bài toán giày
M_shoes = np.array([[0.8, 0.3], [0.2, 0.7]])
steady_state = analyze_markov_matrix(M_shoes, "giày", 100)

# Ma trận Markov đặc biệt
M_special = np.array([[0.5, 0.5], [0.5, 0.5]])
analyze_markov_matrix(M_special, "đặc biệt", 10)

5. PHÂN RÃ MA TRẬN LU

In [ ]:
def lu_decomposition_demo(matrix, name):
    print(f"\nPhân rã LU cho ma trận {name}:")
    print(f"Ma trận gốc:\n{matrix}")
    
    try:
        P, L, U = linalg.lu(matrix)
        print(f"Ma trận P (hoán vị):\n{P}")
        print(f"Ma trận L (tam giác dưới):\n{L}")
        print(f"Ma trận U (tam giác trên):\n{U}")
        
        # Kiểm tra P @ L @ U = A
        reconstructed = P @ L @ U
        print(f"Kiểm tra P @ L @ U:\n{reconstructed}")
        print(f"Sai số: {np.max(np.abs(reconstructed - matrix))}")
        
    except Exception as e:
        print(f"Lỗi trong phân rã LU: {e}")

# Test với các ma trận khác nhau
test_matrices = [
    (np.array([[2, 1], [1, 1]]), "2x2"),
    (np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]]), "3x3"),
    (M_shoes, "Markov")
]

for matrix, name in test_matrices:
    lu_decomposition_demo(matrix, name)

6. BÀI TOÁN LOAN TIN

In [ ]:
def analyze_communication_network(A, max_steps=5):
    """Phân tích mạng truyền thông tin"""
    print("Ma trận kết nối ban đầu:")
    print(A)
    
    n = A.shape[0]
    cumulative = A.copy()
    current_power = A.copy()
    
    print(f"\nPhân tích các bước truyền tin:")
    for step in range(1, max_steps + 1):
        print(f"\nBước {step} (A^{step}):")
        print(current_power)
        
        if step > 1:
            cumulative += current_power
        
        if step < max_steps:
            current_power = current_power @ A
    
    print(f"\nTổng số cách truyền tin từ bước 1 đến {max_steps}:")
    print(cumulative)
    
    # Phân tích một số kết nối cụ thể
    print(f"\nPhân tích chi tiết:")
    for i in range(n):
        for j in range(n):
            if i != j and cumulative[i, j] > 0:
                print(f"Từ người {i+1} đến người {j+1}: {cumulative[i, j]} cách")

# Ma trận truyền tin từ tài liệu
communication_matrix = np.array([
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [1, 1, 0, 0]
])

analyze_communication_network(communication_matrix, 3)