In [1]:
import numpy as np
scores = np.array([-1,12,-3,5,-4])
print(scores)
print(scores>=0)
print(scores<0)
print(np.select([scores >=0, scores < 0],['so duong', 'so am']))

[-1 12 -3  5 -4]
[False  True False  True False]
[ True False  True False  True]
['so am' 'so duong' 'so am' 'so duong' 'so am']


In [2]:
import numpy as np
scores = np.array([-1,1,2,0,-3,5,-4])
print(np.select([scores >=0, scores < 0],['so duong', 'so am']))

['so am' 'so duong' 'so duong' 'so duong' 'so am' 'so duong' 'so am']


Bai 3

In [3]:
import numpy as np
from scipy import linalg, sparse

D = np.mat([[3,4],[5,6]])
print(D)

[[3 4]
 [5 6]]


In [5]:
import numpy as np
from scipy import linalg, sparse
C = np.mat(np.random.random((5,7)))
print(C)

[[0.60737112 0.61771045 0.11949663 0.65279074 0.46253093 0.74363626
  0.20854409]
 [0.24355066 0.49297766 0.2743474  0.5389431  0.1259685  0.09083301
  0.72830797]
 [0.01843692 0.99660375 0.34306647 0.52195443 0.76767409 0.21209513
  0.74141161]
 [0.97179722 0.04753631 0.07768935 0.04688915 0.76150662 0.06128953
  0.68283383]
 [0.7163255  0.65863893 0.45003411 0.17919075 0.21004604 0.24767881
  0.46989887]]


In [6]:
A = np.mat(np.random.random((2,2)))
print(A)

[[0.36895288 0.64434885]
 [0.43667634 0.80878991]]


In [7]:
b = np.array([(1+5j, 2j, 3j),(4, 5,6)]) 
print(b)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [8]:
B = np.asmatrix(b)
print(B)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [11]:
print(A.T)
print(A.I)
print(linalg.inv(A))

[[0.36895288 0.43667634]
 [0.64434885 0.80878991]]
[[ 47.48239708 -37.82839965]
 [-25.63637245  21.66046694]]
[[ 47.48239708 -37.82839965]
 [-25.63637245  21.66046694]]


In [12]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
print(M_lower)

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [13]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper = np.triu(M)
print(M_upper)

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [14]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]]) 
v_diag = np.diag(M)
print(v_diag)
M_diag = np.diag(v_diag)
print(M_diag)

[-1 -2 -2]
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [ ]:
import sympy as sp 
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
print(sp.solve ( [x*x+2-6, y-1-6,x+z-1, 2*x*x-8, z*z+4-5, y-z-8],[x,y,z] ) )

[(2, 7, -1)]


In [18]:
A = ([[0,1,2,3,4,5],
      [6,7,8,9,10,11],
      [12,13,14,15,16,17],
      [18,19,20,21,22,23],
      [24,25,26,27,28,29],
      [30,31,32,33,34,35]])
I = ([[1,0,0,0,0,0],
      [0,1,0,0,0,0],
      [0,0,1,0,0,0],
      [0,0,0,1,0,0],
      [0,0,0,0,1,0],
      [0,0,0,0,0,1]])
A = np.reshape(np.arange(36.0),(6,6))
print(A)
I6 = np.identity(6)
print(I6)

print(A.size)
print(np.matrix.diagonal(A))
A_sum = A + I6
print(A_sum)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
36
[ 0.  7. 14. 21. 28. 35.]
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [20]:
vecB = np.array([1.,2.,3.,4.,5.,6.])
C = A.dot(vecB)
print("C = ",C)

C =  [ 70. 196. 322. 448. 574. 700.]


In [21]:
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print("D = ",D)

E = A.dot(D)
print("E = ", E)

D =  [[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]


ValueError: shapes (6,6) and (2,6) not aligned: 6 (dim 1) != 2 (dim 0)

In [25]:
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)
print("F = ", F)
print("G = ", G)
print("A.T = ", np.linalg.inv(np.linalg.inv(A)))


F =  [[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
G =  [[ 70.   6.]
 [196.  24.]
 [322.  42.]
 [448.  60.]
 [574.  78.]
 [700.  96.]]


LinAlgError: Singular matrix

# Bai 4

In [26]:
A = np.array([[1,1], [1,0]])
b = np.array([1,0])
n = 10
for i in range(n):
    b = A.dot(b)
    print("b = ",b)

b =  [1 1]
b =  [2 1]
b =  [3 2]
b =  [5 3]
b =  [8 5]
b =  [13  8]
b =  [21 13]
b =  [34 21]
b =  [55 34]
b =  [89 55]


# Bai 5

In [28]:
import sympy as sp
from sympy import Symbol, solve

x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')

pt1 = x4 + 610 - 450 - x1
pt2 = x1 + 400 -x2 - 640
pt3 = x2 + 600 -x3
pt4 = x3 -x4 - 520

nghiem = sp.solve((pt1,pt2,pt3,pt4))
print("nghiem = ", nghiem)

nghiem =  {x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


In [31]:
A = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])
A_nghichdao = np.linalg.pinv(A)
print("A_nghichdao = ", A_nghichdao)

A_nghichdao =  [[-0.375  0.375  0.125 -0.125]
 [-0.125 -0.375  0.375  0.125]
 [ 0.125 -0.125 -0.375  0.375]
 [ 0.375  0.125 -0.125 -0.375]]


# Bai tap chuong

# Bai 1

Van de 1:

In [32]:
from scipy.integrate import quad

A1 = np.array([[1, -1], 
               [2, 3]])
b1 = np.array([-2, 6])

solution1 = np.linalg.solve(A1, b1)
print(f"\nNghiệm: x = {solution1[0]:.2f}, y = {solution1[1]:.2f}")


print(f"Kiểm tra: {solution1[0]} - {solution1[1]} = {solution1[0] - solution1[1]:.2f}")
print(f"Kiểm tra: 2×{solution1[0]} + 3×{solution1[1]} = {2*solution1[0] + 3*solution1[1]:.2f}")

print("\n" + "="*60)


Nghiệm: x = 0.00, y = 2.00
Kiểm tra: 0.0 - 2.0 = -2.00
Kiểm tra: 2×0.0 + 3×2.0 = 6.00



Van de 2:

In [33]:
A2 = np.array([[1, -1, 0],
               [2, -1, -1],
               [1, 1, 1]])
b2 = np.array([2, 3, 6])

det_A2 = np.linalg.det(A2)
print(f"\nDeterminant của ma trận hệ số: {det_A2:.2f}")

if abs(det_A2) > 1e-10:
    solution2 = np.linalg.solve(A2, b2)
    print(f"Nghiệm: x = {solution2[0]:.2f}, y = {solution2[1]:.2f}, z = {solution2[2]:.2f}")
    
    print(f"Kiểm tra:")
    print(f"  {solution2[0]:.2f} - {solution2[1]:.2f} = {solution2[0] - solution2[1]:.2f}")
    print(f"  2×{solution2[0]:.2f} - {solution2[1]:.2f} - {solution2[2]:.2f} = {2*solution2[0] - solution2[1] - solution2[2]:.2f}")
    print(f"  {solution2[0]:.2f} + {solution2[1]:.2f} + {solution2[2]:.2f} = {solution2[0] + solution2[1] + solution2[2]:.2f}")
else:
    print("Hệ phương trình không có nghiệm duy nhất")

print("\n" + "="*60)


Determinant của ma trận hệ số: 3.00
Nghiệm: x = 3.00, y = 1.00, z = 2.00
Kiểm tra:
  3.00 - 1.00 = 2.00
  2×3.00 - 1.00 - 2.00 = 3.00
  3.00 + 1.00 + 2.00 = 6.00



Van de 3:

In [34]:
A3 = np.array([[1, 1, 1],
               [4, 2, 1],
               [9, 3, 1]])
b3 = np.array([4, 3, 4])

solution3 = np.linalg.solve(A3, b3)
a, b, c = solution3

print(f"Các hệ số: a = {a:.2f}, b = {b:.2f}, c = {c:.2f}")
print(f"Đa thức: p(x) = {a:.2f}x² + {b:.2f}x + {c:.2f}")

print(f"Kiểm tra:")
print(f"  p(1) = {a + b + c:.2f}")
print(f"  p(2) = {4*a + 2*b + c:.2f}")
print(f"  p(3) = {9*a + 3*b + c:.2f}")

print("\n" + "="*60)


Các hệ số: a = 1.00, b = -4.00, c = 7.00
Đa thức: p(x) = 1.00x² + -4.00x + 7.00
Kiểm tra:
  p(1) = 4.00
  p(2) = 3.00
  p(3) = 4.00



Van de 4:

In [35]:
A4 = np.array([[1, 0, 1],
               [1, 1, -2],
               [-2, 2, 1]])
b4 = np.array([1, -3, 0])

solution4 = np.linalg.solve(A4, b4)
a4, b4_coeff, c4 = solution4

print(f"Các hệ số: a = {a4:.2f}, b = {b4_coeff:.2f}, c = {c4:.2f}")
print(f"Phân tích: R(x) = {a4:.2f}/(x-1) + {b4_coeff:.2f}/(x-1)² + {c4:.2f}/(x+2)")

print("\n" + "="*60)

Các hệ số: a = -0.11, b = -0.67, c = 1.11
Phân tích: R(x) = -0.11/(x-1) + -0.67/(x-1)² + 1.11/(x+2)



# Cau 3

In [36]:
F = np.array([[1, 1], [1, 0]], dtype=np.int64)
print(f"Ma trận F:")
print(F)

print(f"\nCác lũy thừa của F:")
for k in range(1, 6):
    F_k = np.linalg.matrix_power(F, k)
    print(f"F^{k} =")
    print(F_k)
    
    if k >= 2:
        fib_k_plus_1 = F_k[0, 0]  # F_{k+1}
        fib_k = F_k[0, 1]         # F_k  
        fib_k_minus_1 = F_k[1, 0] # F_{k-1}
        print(f"  → Fibo_{k+1} = {fib_k_plus_1}, Fibo_{k} = {fib_k}, Fibo_{k-1} = {fib_k_minus_1}")
    print()

k = 10
F_10 = np.linalg.matrix_power(F, k)
print(f"F^{k} =")
print(F_10)
print(f"  → Fibo_{k+1} = {F_10[0,0]}, Fibo_{k} = {F_10[0,1]}, Fibo_{k-1} = {F_10[1,0]}")

print("\n" + "="*60)

Ma trận F:
[[1 1]
 [1 0]]

Các lũy thừa của F:
F^1 =
[[1 1]
 [1 0]]

F^2 =
[[2 1]
 [1 1]]
  → Fibo_3 = 2, Fibo_2 = 1, Fibo_1 = 1

F^3 =
[[3 2]
 [2 1]]
  → Fibo_4 = 3, Fibo_3 = 2, Fibo_2 = 2

F^4 =
[[5 3]
 [3 2]]
  → Fibo_5 = 5, Fibo_4 = 3, Fibo_3 = 3

F^5 =
[[8 5]
 [5 3]]
  → Fibo_6 = 8, Fibo_5 = 5, Fibo_4 = 5

F^10 =
[[89 55]
 [55 34]]
  → Fibo_11 = 89, Fibo_10 = 55, Fibo_9 = 55

