LAB 4

Bài 1

In [3]:
import numpy as np
import math
from itertools import permutations

n = 4
X = np.array(range(1,n+1))
sigma = np.array([4,3,2,1])

def sgn_by_def(sigma):
    ket_qua = 1.0
    for i in range(len(X)-1):
        for j in range(i+1,len(X)):
            ket_qua = ket_qua * ((X[i] - X[j]))/(sigma[i] - sigma[j])
            return int(ket_qua)
sigma = np.array([2,1,3,4])
print(sgn_by_def(sigma))


-1


In [4]:
sigma1 = np.array([1,2,3,4])
print(sgn_by_def(sigma1))

1


In [5]:
sigma2 = np.array([4,3,2,1]) 
print(sgn_by_def(sigma2))

-1


In [8]:
from itertools import permutations
n = 3
X = []
for i in range (1, n+1):
    X.append(i)
Sn = list(permutations(X)) #  tạo hoán vị của tập X
print (Sn)

det = 0

def phatsinh_DT(n):
    X = []
    for i in range(1,n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = ""
    for sn in Sn:
        sigma3 = np.array([1])
        sigma3.resize([n])
        product = ""
        for i in range(1,n+1):
            sigma3[sn.index(i)] = i
            product = product + "a" + str(sn.index(i) + 1)
        dau = sgn_by_def(sigma3)
        if (dau != 1):
            product = " - " + product
        else:
            product = " + " + product
        dinhthuc = dinhthuc + product
    return dinhthuc
print(phatsinh_DT(2))
print(phatsinh_DT(3))


[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]
 + a1a2 - a2a1
 + a1a2a3 - a1a3a2 - a2a1a3 + a3a1a2 - a2a3a1 - a3a2a1


In [11]:
def tinhtoan_dinhthuc(A):
    X = []
    import math
    n = int(math.sqrt(A.size))
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = 0
    for sn in Sn:
        sigma = np.zeros(n, dtype=int)
        product = 1
        
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product * A[i-1][sn.index(i)]
        
        dau = sgn_by_def(sigma)
        if dau != 1:
            product = product * (-1)
        
        dinhthuc = dinhthuc + product
    
    return dinhthuc
matran = np.array([ [3,5,-8], [4, 12, -1], [2,5,3] ]) 
A = np.array([[1, 2], [3, 4]])
print(tinhtoan_dinhthuc(A))

-2


Bài 3

In [13]:
import numpy as np
A = np.array([[4, -2],[3, -5]]) # khai báo ma trận A
A1 = np.array([[10, -2],[11, -5]])
A2 = np.array([[4, 10],[3, 11]])
from scipy import linalg # lưu ý: hàm tính định thức của ma trận là scipy.linalg.det(A)
detA = linalg.det(A) # tính định thức cho ma trận A
detA1 = linalg.det(A1)
detA2 = linalg.det(A2)
print (detA, detA1, detA2) 

if (detA != 0):
    x1 = detA1 / detA
    x2 = detA2 / detA
print ("Hai nghiệm của phương trình là: ", x1, x2)

-14.0 -28.0 14.000000000000004
Hai nghiệm của phương trình là:  2.0 -1.0000000000000002


In [14]:
import numpy as np
from scipy.linalg import det

def tinhtoan_dinhthuc(A):
    X = []
    n = int(np.sqrt(A.size))
    
    for i in range(1, n+1):
        X.append(i)
    
    from itertools import permutations
    Sn = list(permutations(X))
    dinhthuc = 0
    
    for sn in Sn:
        sigma = np.zeros(n, dtype=int)
        product = 1
        
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product * A[i-1][sn.index(i)]
        
        dau = sgn_by_def(sigma)
        if dau != 1:
            product = product * (-1)
        
        dinhthuc = dinhthuc + product
    
    return dinhthuc

def sgn_by_def(sigma):
    n = len(sigma)
    inversions = 0
    
    for i in range(n):
        for j in range(i+1, n):
            if sigma[i] > sigma[j]:
                inversions += 1
    
    return 1 if inversions % 2 == 0 else -1

# Hệ phương trình:
# -x + 2y - 3z = 1
# 2x - 2y + z = 3  
# 3x - 4y + 4z = 2

# Ma trận hệ số A
A = np.array([[-1, 2, -3],
              [2, -2, 1],
              [3, -4, 4]])

# Vector hằng số b
b = np.array([1, 3, 2])

print("Phương pháp 1: Sử dụng hàm det() của scipy")
det_A = det(A)
print(f"det(A) = {det_A}")

if det_A != 0:
    # Tính nghiệm bằng quy tắc Cramer
    A_x = A.copy()
    A_x[:, 0] = b
    x = det(A_x) / det_A
    
    A_y = A.copy()  
    A_y[:, 1] = b
    y = det(A_y) / det_A
    
    A_z = A.copy()
    A_z[:, 2] = b  
    z = det(A_z) / det_A
    
    print(f"Nghiệm: x = {x}, y = {y}, z = {z}")
else:
    print("Hệ vô nghiệm hoặc vô số nghiệm")

print("\nPhương pháp 2: Sử dụng hàm tinhtoan_dinhthuc() viết bên trên")
det_A_custom = tinhtoan_dinhthuc(A)
print(f"det(A) = {det_A_custom}")

if det_A_custom != 0:
    A_x = A.copy()
    A_x[:, 0] = b
    x = tinhtoan_dinhthuc(A_x) / det_A_custom
    
    A_y = A.copy()
    A_y[:, 1] = b  
    y = tinhtoan_dinhthuc(A_y) / det_A_custom
    
    A_z = A.copy()
    A_z[:, 2] = b
    z = tinhtoan_dinhthuc(A_z) / det_A_custom
    
    print(f"Nghiệm: x = {x}, y = {y}, z = {z}")
else:
    print("Hệ vô nghiệm hoặc vô số nghiệm")

print(f"\nKhai báo ma trận: A = \n{A}")
print(f"Vector b = {b}")

Phương pháp 1: Sử dụng hàm det() của scipy
det(A) = 0.0
Hệ vô nghiệm hoặc vô số nghiệm

Phương pháp 2: Sử dụng hàm tinhtoan_dinhthuc() viết bên trên
det(A) = 0
Hệ vô nghiệm hoặc vô số nghiệm

Khai báo ma trận: A = 
[[-1  2 -3]
 [ 2 -2  1]
 [ 3 -4  4]]
Vector b = [1 3 2]


Ứng dụng 1:

In [20]:
import sympy as sp 
TG = sp.Matrix([[1,0,1],[4,3,1],[2,2,1]])
print("Dien tich tam giac la: " , (1/2 *TG.det()))

Dien tich tam giac la:  1.50000000000000


Ứng dụng 2:

In [22]:
from sympy import Matrix

M = Matrix([[0, 4, 1, 1], [4, 0, 0, 1], [3, 5, 2, 1], [2, 2, 5, 1]])
print("The tich hinh tu dien: ", 1/6*M.det())
print("The tich hinh tu dien: ", M.det())


The tich hinh tu dien:  -12.0000000000000
The tich hinh tu dien:  -72


Ứng dụng 4:

In [23]:
from sympy import * # lúc này ta sử dụng trực tiếp thư viện 

x, y, z = symbols('x y z')
MP = Matrix([[x, y, z, 1],[-1, 3, 2, 1],[0, 1, 0, 1],[-2, 0, 1, 1]])
print(M.det())

-72


Bài toán ứng dụng 3:

In [26]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import least_squares
import sympy as sp

def fit_ellipse_general(x_points, y_points):
    """
    Fitting ellipse với phương trình tổng quát: ax² + bxy + cy² + dx + ey + f = 0
    Sử dụng phương pháp bình phương tối thiểu
    """
    n = len(x_points)
    
    # Tạo ma trận A cho hệ phương trình
    A = np.zeros((n, 6))
    for i in range(n):
        x, y = x_points[i], y_points[i]
        A[i] = [x**2, x*y, y**2, x, y, 1]
    
    # Giải hệ phương trình bằng SVD (Singular Value Decomposition)
    U, s, Vt = np.linalg.svd(A)
    
    # Nghiệm là vector riêng ứng với giá trị riêng nhỏ nhất
    coeffs = Vt[-1, :]
    
    return coeffs

def ellipse_parameters(coeffs):
    """
    Chuyển đổi từ dạng tổng quát sang dạng tham số của ellipse
    """
    a, b, c, d, e, f = coeffs
    
    # Tính tâm ellipse
    det = b**2 - 4*a*c
    if abs(det) < 1e-10:
        return None  # Không phải ellipse
    
    x0 = (2*c*d - b*e) / det
    y0 = (2*a*e - b*d) / det
    
    # Tính các tham số khác
    num = 2*(a*e**2 + c*d**2 + f*b**2 - 2*b*d*e - 4*a*c*f)
    den1 = (det) * (np.sqrt((a-c)**2 + b**2) - (a+c))
    den2 = (det) * (-np.sqrt((a-c)**2 + b**2) - (a+c))
    
    if den1 > 0 and den2 > 0:
        semi_major = np.sqrt(num / den1)
        semi_minor = np.sqrt(num / den2)
    else:
        return None
    
    # Góc xoay
    if abs(b) < 1e-10:
        angle = 0 if a < c else np.pi/2
    else:
        angle = 0.5 * np.arctan(b / (a - c))
    
    return x0, y0, semi_major, semi_minor, angle

def generate_ellipse_points(x0, y0, a, b, angle, n_points=100):
    """
    Tạo các điểm trên ellipse
    """
    t = np.linspace(0, 2*np.pi, n_points)
    
    # Ellipse trong hệ tọa độ địa phương
    x_local = a * np.cos(t)
    y_local = b * np.sin(t)
    
    # Xoay và dịch chuyển
    cos_angle = np.cos(angle)
    sin_angle = np.sin(angle)
    
    x = x0 + x_local * cos_angle - y_local * sin_angle
    y = y0 + x_local * sin_angle + y_local * cos_angle
    
    return x, y

# Ví dụ: Mô phỏng quỹ đạo hành tinh
print("=== TÍNH QUỸ ĐẠO CỦA HÀNH TINH/VỆ TINH ===")
print("Sử dụng phương pháp fitting ellipse với dữ liệu quan sát")

# Tạo dữ liệu mẫu (giả lập quan sát quỹ đạo)
np.random.seed(42)
true_x0, true_y0 = 2, 1  # Tâm ellipse
true_a, true_b = 5, 3    # Bán trục lớn và nhỏ
true_angle = np.pi/6     # Góc xoay

# Tạo điểm quan sát với nhiễu
n_obs = 20
t_obs = np.sort(np.random.uniform(0, 2*np.pi, n_obs))
x_true, y_true = generate_ellipse_points(true_x0, true_y0, true_a, true_b, true_angle, n_obs)

# Thêm nhiễu quan sát
noise_level = 0.2
x_obs = x_true + np.random.normal(0, noise_level, n_obs)
y_obs = y_true + np.random.normal(0, noise_level, n_obs)

print(f"\nSố điểm quan sát: {n_obs}")
print("Dữ liệu quan sát (x, y):")
for i in range(min(5, n_obs)):
    print(f"  Điểm {i+1}: ({x_obs[i]:.3f}, {y_obs[i]:.3f})")
print("  ...")

# Tạo ma trận hệ phương trình như trong đề bài
print(f"\nMa trận hệ phương trình A (6 điểm đầu):")
A_matrix = np.zeros((min(6, n_obs), 6))
for i in range(min(6, n_obs)):
    x, y = x_obs[i], y_obs[i]
    A_matrix[i] = [x**2, x*y, y**2, x, y, 1]

print("     x²      xy      y²       x       y       1")
for i in range(min(6, n_obs)):
    print(f"{A_matrix[i, 0]:8.3f} {A_matrix[i, 1]:8.3f} {A_matrix[i, 2]:8.3f} {A_matrix[i, 3]:8.3f} {A_matrix[i, 4]:8.3f} {A_matrix[i, 5]:8.3f}")

# Fitting ellipse
coeffs = fit_ellipse_general(x_obs, y_obs)
print(f"\nHệ số ellipse tìm được:")
print(f"a = {coeffs[0]:.6f}")
print(f"b = {coeffs[1]:.6f}") 
print(f"c = {coeffs[2]:.6f}")
print(f"d = {coeffs[3]:.6f}")
print(f"e = {coeffs[4]:.6f}")
print(f"f = {coeffs[5]:.6f}")

print(f"\nPhương trình ellipse:")
print(f"{coeffs[0]:.3f}x² + {coeffs[1]:.3f}xy + {coeffs[2]:.3f}y² + {coeffs[3]:.3f}x + {coeffs[4]:.3f}y + {coeffs[5]:.3f} = 0")

# Tính tham số ellipse
params = ellipse_parameters(coeffs)
if params:
    x0, y0, semi_major, semi_minor, angle = params
    print(f"\nTham số ellipse:")
    print(f"Tâm: ({x0:.3f}, {y0:.3f})")
    print(f"Bán trục lớn: {max(semi_major, semi_minor):.3f}")
    print(f"Bán trục nhỏ: {min(semi_major, semi_minor):.3f}")
    print(f"Góc xoay: {angle*180/np.pi:.1f}°")
    
    # Vẽ đồ thị
    plt.figure(figsize=(10, 8))
    
    # Vẽ điểm quan sát
    plt.scatter(x_obs, y_obs, color='red', s=50, label='Điểm quan sát', zorder=3)
    
    # Vẽ ellipse fitting
    x_fit, y_fit = generate_ellipse_points(x0, y0, max(semi_major, semi_minor), 
                                         min(semi_major, semi_minor), angle, 200)
    plt.plot(x_fit, y_fit, 'b-', linewidth=2, label='Ellipse fitting')
    
    # Vẽ ellipse thực (để so sánh)
    x_true_full, y_true_full = generate_ellipse_points(true_x0, true_y0, true_a, true_b, true_angle, 200)
    plt.plot(x_true_full, y_true_full, 'g--', linewidth=2, label='Ellipse thực', alpha=0.7)
    
    # Vẽ tâm
    plt.plot(x0, y0, 'bo', markersize=8, label=f'Tâm fitting ({x0:.2f}, {y0:.2f})')
    plt.plot(true_x0, true_y0, 'go', markersize=8, label=f'Tâm thực ({true_x0}, {true_y0})')
    
    plt.grid(True, alpha=0.3)
    plt.axis('equal')
    plt.legend()
    plt.title('Fitting Quỹ Đạo Ellipse của Hành Tinh/Vệ Tinh')
    plt.xlabel('X (đơn vị thiên văn)')
    plt.ylabel('Y (đơn vị thiên văn)')
    
    plt.tight_layout()
    plt.savefig('ellipse_orbit.png', dpi=300, bbox_inches='tight')
    plt.show()
    
else:
    print("Không thể xác định được tham số ellipse!")



=== TÍNH QUỸ ĐẠO CỦA HÀNH TINH/VỆ TINH ===
Sử dụng phương pháp fitting ellipse với dữ liệu quan sát

Số điểm quan sát: 20
Dữ liệu quan sát (x, y):
  Điểm 1: (6.128, 3.542)
  Điểm 2: (5.671, 3.816)
  Điểm 3: (4.314, 4.303)
  Điểm 4: (2.830, 4.582)
  Điểm 5: (1.902, 4.280)
  ...

Ma trận hệ phương trình A (6 điểm đầu):
     x²      xy      y²       x       y       1
  37.547   21.702   12.544    6.128    3.542    1.000
  32.164   21.643   14.563    5.671    3.816    1.000
  18.612   18.564   18.516    4.314    4.303    1.000
   8.010   12.967   20.993    2.830    4.582    1.000
   3.618    8.141   18.318    1.902    4.280    1.000
   0.010    0.350   11.676    0.102    3.417    1.000

Hệ số ellipse tìm được:
a = -0.065146
b = 0.062385
c = -0.107047
d = 0.193551
e = 0.077261
f = 0.967974

Phương trình ellipse:
-0.065x² + 0.062xy + -0.107y² + 0.194x + 0.077y + 0.968 = 0
Không thể xác định được tham số ellipse!


BÀI TẬP CHƯƠNG 4

Câu 1:

In [29]:
import numpy as np
import sympy as sp
from sympy import symbols, Matrix, det, simplify
import matplotlib.pyplot as plt

def calculate_minor(matrix, i, j):
    n = matrix.shape[0]
    # Tạo ma trận con bằng cách bỏ hàng i và cột j
    minor_matrix = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
    return np.linalg.det(minor_matrix)

def cofactor_matrix(matrix):
    n = matrix.shape[0]
    cofactor_mat = np.zeros((n, n))
    
    for i in range(n):
        for j in range(n):
            # Tính minor
            minor = calculate_minor(matrix, i, j)
            # Cofactor = (-1)^(i+j) * minor
            cofactor_mat[i][j] = ((-1) ** (i + j)) * minor
    
    return cofactor_mat

def adjoint_matrix(matrix):
    # Ma trận liên hợp = chuyển vị của ma trận hệ số kép
    cofactor_mat = cofactor_matrix(matrix)
    return cofactor_mat.T

def matrix_inverse_using_adjoint(matrix):
    det_A = np.linalg.det(matrix)
    if abs(det_A) < 1e-10:
        print("Ma trận không khả nghịch (định thức = 0)")
        return None
    
    adj_A = adjoint_matrix(matrix)
    return adj_A / det_A

# Test câu 1
# Ví dụ ma trận 3x3
A = np.array([[1, 2, 3],
              [0, 1, 4], 
              [5, 6, 0]], dtype=float)

print("Ma trận A:")
print(A)
print()

# Tính ma trận hệ số kép
cofactor_A = cofactor_matrix(A)
print("Ma trận hệ số kép (Cofactor Matrix):")
print(cofactor_A)
print()

# Tính ma trận liên hợp
adj_A = adjoint_matrix(A)
print("Ma trận liên hợp (Adjoint Matrix):")
print(adj_A)
print()

# Tính ma trận nghịch đảo
inv_A = matrix_inverse_using_adjoint(A)
print("Ma trận nghịch đảo (sử dụng adjoint):")
print(inv_A)
print()

# Kiểm tra với numpy
inv_A_numpy = np.linalg.inv(A)
print("Ma trận nghịch đảo (NumPy):")
print(inv_A_numpy)
print()

# Kiểm tra A * A^(-1) = I
print("Kiểm tra A * A^(-1):")
print(np.dot(A, inv_A))
print()

Ma trận A:
[[1. 2. 3.]
 [0. 1. 4.]
 [5. 6. 0.]]

Ma trận hệ số kép (Cofactor Matrix):
[[-24.  20.  -5.]
 [ 18. -15.   4.]
 [  5.  -4.   1.]]

Ma trận liên hợp (Adjoint Matrix):
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

Ma trận nghịch đảo (sử dụng adjoint):
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

Ma trận nghịch đảo (NumPy):
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

Kiểm tra A * A^(-1):
[[ 1.00000000e+00 -6.21724894e-15  8.88178420e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 7.10542736e-15 -2.13162821e-14  1.00000000e+00]]



Câu 2:

In [32]:
def circle_through_three_points(x1, y1, x2, y2, x3, y3):
    # Định nghĩa biến symbolic
    x, y = symbols('x y')
    
    # Tạo ma trận định thức
    matrix = Matrix([
        [x**2 + y**2, x, y, 1],
        [x1**2 + y1**2, x1, y1, 1],
        [x2**2 + y2**2, x2, y2, 1],
        [x3**2 + y3**2, x3, y3, 1]
    ])
    
    # Tính định thức
    circle_eq = det(matrix)
    circle_eq = simplify(circle_eq)
    
    return circle_eq, x, y

def extract_circle_parameters(circle_eq, x, y):
    # Khai triển phương trình
    expanded = sp.expand(circle_eq)
    
    # Thu thập hệ số
    coeffs = sp.Poly(expanded, [x, y]).all_coeffs()
    
    
    # Chia phương trình cho hệ số của x² để chuẩn hóa
    print("Phương trình đường tròn:")
    print(f"{circle_eq} = 0")
    
    return expanded

def plot_circle_and_points(x1, y1, x2, y2, x3, y3, center_x=None, center_y=None, radius=None):
    plt.figure(figsize=(10, 8))
    
    # Vẽ các điểm đã cho
    plt.plot([x1, x2, x3], [y1, y2, y3], 'ro', markersize=8, label='Điểm đã cho')
    plt.annotate(f'P1({x1},{y1})', (x1, y1), xytext=(5, 5), textcoords='offset points')
    plt.annotate(f'P2({x2},{y2})', (x2, y2), xytext=(5, 5), textcoords='offset points')
    plt.annotate(f'P3({x3},{y3})', (x3, y3), xytext=(5, 5), textcoords='offset points')
    
    if center_x is not None and center_y is not None and radius is not None:
        # Vẽ đường tròn
        theta = np.linspace(0, 2*np.pi, 100)
        circle_x = center_x + radius * np.cos(theta)
        circle_y = center_y + radius * np.sin(theta)
        plt.plot(circle_x, circle_y, 'b-', linewidth=2, label='Đường tròn')
        
        # Vẽ tâm
        plt.plot(center_x, center_y, 'g*', markersize=10, label=f'Tâm ({center_x:.2f},{center_y:.2f})')
    
    plt.grid(True, alpha=0.3)
    plt.axis('equal')
    plt.legend()
    plt.title('Đường tròn đi qua 3 điểm')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.show()

# Test câu 2
# Ví dụ với 3 điểm
x1, y1 = 1, 1
x2, y2 = 4, 2
x3, y3 = 3, 5

print(f"Ba điểm đã cho:")
print(f"P1({x1}, {y1})")
print(f"P2({x2}, {y2})")
print(f"P3({x3}, {y3})")
print()




Ba điểm đã cho:
P1(1, 1)
P2(4, 2)
P3(3, 5)

